gem_hack/spree_mail_settings-2-4/config/routes.rb
Spree::Core::Engine.routes.append do
  namespace :admin do
    resource :mail_method, only: [:edit, :update] do
      post :testmail, on: :collection
    end
  end
end

gem_hack/spree_mail_settings-2-4/app/models/spree/app_configuration_decorator.rb
module Spree
  AppConfiguration.class_eval do
    # Default mail headers settings
    preference :enable_mail_delivery, :boolean, default: false
    preference :mail_bcc, :string, default: 'spree@example.com'
    preference :intercept_email, :string, default: nil
    
    # Default smtp settings
    preference :mail_host, :string, default: 'localhost'
    preference :mail_domain, :string, default: 'localhost'
    preference :mail_port, :integer, default: 25
    preference :secure_connection_type, :string, default: Core::MailSettings::SECURE_CONNECTION_TYPES[0]
    preference :mail_auth_type, :string, default: Core::MailSettings::MAIL_AUTH[0]
    preference :smtp_username, :string
    preference :smtp_password, :string

    def override_actionmailer_config
      raise "override_actionmailer_config has been removed. actionmailer's config is always overwridden when spree_mail_settings is included"
    end
    alias_method :override_actionmailer_config=, :override_actionmailer_config
  end
end

gem_hack/spree_mail_settings-2-4/app/controllers/spree/admin/mail_methods_controller.rb
module Spree
  module Admin
    class MailMethodsController < BaseController
      def update
        params.delete(:smtp_password) if params[:smtp_password].blank?

        params.each do |name, value|
          next unless Spree::Config.has_preference? name
          Spree::Config[name] = value
        end

        flash[:success] = Spree.t(:successfully_updated, resource: Spree.t(:mail_method_settings))
        redirect_to edit_admin_mail_method_url
      end

      def testmail
        if TestMailer.test_email(try_spree_current_user.email).deliver
          flash[:success] = Spree.t('mail_methods.testmail.delivery_success')
        else
          flash[:error] = Spree.t('mail_methods.testmail.delivery_error')
        end
      rescue => e
        flash[:error] = Spree.t('mail_methods.testmail.error') % { e: e }
      ensure
        redirect_to edit_admin_mail_method_url
      end
    end
  end
end

gem_hack/spree_mail_settings-2-4/app/views/spree/admin/mail_methods/_form.html.erb
<div data-hook="admin_mail_method_form_fields">
  <div class="row">

    <div class="alpha six columns" data-hook="general">
      <fieldset class="no-border-bottom">
        <legend align="center"><%= Spree.t(:general) %></legend>

        <div class="field">
          <%= preference_field_tag("enable_mail_delivery", Spree::Config[:enable_mail_delivery], type: :boolean) %>
          <%= label_tag :enable_mail_delivery, Spree.t(:enable_mail_delivery) %>
        </div>

        <!--div class="field">
          <%#= label_tag :mails_from, Spree.t(:send_mails_as) %><br />
          <%#= text_field_tag :mails_from, Spree::Config[:mails_from], maxlength: 256, class: 'fullwidth' %>
          <br />
          <span class="info">
            <%#= Spree.t(:smtp_send_all_emails_as_from_following_address) %>
          </span>
        </div-->

        <div class="field">
          <%= label_tag :mail_bcc, Spree.t(:send_copy_of_all_mails_to) %><br />
          <%= text_field_tag :mail_bcc, Spree::Config[:mail_bcc], maxlength: 256, class: 'fullwidth' %>
          <br />
          <span class="info">
            <%= Spree.t(:smtp_send_copy_to_this_addresses) %>
          </span>
        </div>

        <div class="field">
          <%= label_tag :intercept_email, Spree.t(:intercept_email_address) %><br />
          <%= text_field_tag :intercept_email, Spree::Config[:intercept_email], maxlength: 256, class: 'fullwidth' %>
          <br />
          <span class="info">
            <%= Spree.t(:intercept_email_instructions) %>
          </span>
        </div>
      </fieldset>
    </div>

    <div class="six columns omega" data-hook="smtp">
      <fieldset class="no-border-bottom">
        <legend align="center"><%= Spree.t(:smtp) %></legend>
        <div class="field">
          <%= label_tag :mail_domain, Spree.t(:smtp_domain) %><br />
          <%= text_field_tag :mail_domain, Spree::Config[:mail_domain], class: 'fullwidth' %>
        </div>
        <div class="field">
          <%= label_tag :mail_host, Spree.t(:smtp_mail_host) %><br />
          <%= text_field_tag :mail_host, Spree::Config[:mail_host], class: 'fullwidth' %>
        </div>
        <div class="field">
          <%= label_tag :mail_port, Spree.t(:smtp_port) %><br />
          <%= text_field_tag :mail_port, Spree::Config[:mail_port], class: 'fullwidth' %>
        </div>
        <div class="field">
          <%= label_tag :secure_connection_type, Spree.t(:secure_connection_type) %><br />
          <%= select_tag(:secure_connection_type,
                         options_from_collection_for_select(Spree::Core::MailSettings::SECURE_CONNECTION_TYPES, :to_s, :to_s, Spree::Config[:secure_connection_type]),
                         class: 'select2 fullwidth') %>
        </div>
        <div class="field">
          <%= label_tag :mail_auth_type, Spree.t(:smtp_authentication_type) %><br />
          <%= select_tag(:mail_auth_type,
                         options_from_collection_for_select(Spree::Core::MailSettings::MAIL_AUTH, :to_s, :to_s, Spree::Config[:mail_auth_type]),
                         class: 'select2 fullwidth') %>
        </div>
        <div class="field">
          <%= label_tag :smtp_username, Spree.t(:smtp_username) %><br />
          <%= text_field_tag :smtp_username, Spree::Config[:smtp_username], class: 'fullwidth', autocomplete: 'off' %>
        </div>
        <div class="field">
          <%= label_tag :preferred_smtp_password, Spree.t(:smtp_password) %><br />
          <%= password_field_tag :smtp_password, Spree::Config[:smtp_password], class: 'fullwidth', autocomplete: 'off' %>
        </div>
      </fieldset>
    </div>
  </div>
</div>

gem_hack/spree_mail_settings-2-4/app/views/spree/admin/mail_methods/edit.html.erb
<%= render partial: 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:mail_method_settings) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= link_to_with_icon 'icon-envelope-alt', Spree.t('mail_methods.send_testmail'), testmail_admin_mail_method_path,
      method: :post, title: Spree.t('mail_methods.send_testmail'), class: 'send_mail button no-text' %>
  </li>
<% end %>

<%= render partial: 'spree/shared/error_messages', locals: { target: @mail_method } %>

<%= form_tag admin_mail_method_path, method: :put do |f| %>
  <fieldset class="no-border-top">
    <%= render partial: 'form', locals: { f: f } %>
    <div class="form-buttons filter-actions actions" data-hook="buttons"><%= button Spree.t('actions.update'), 'icon-refresh' %></div>
  </fieldset>
<% end %>