gem_hack/spree_active_shipping_2_4_0/config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resource :active_shipping_settings, :only => ['show', 'update', 'edit']

    resources :products, :only => [] do
      resources :product_packages
    end
  end
end

gem_hack/spree_active_shipping_2_4_0/app/controllers/spree/admin/active_shipping_settings_controller.rb
class Spree::Admin::ActiveShippingSettingsController < Spree::Admin::BaseController

  def edit
    @preferences_UPS = [:ups_login, :ups_password, :ups_key, :shipper_number]
    @preferences_FedEx = [:fedex_login, :fedex_password, :fedex_account, :fedex_key]
    @preferences_USPS = [:usps_login]
    @preferences_CanadaPost = [:canada_post_login]
    @preferences_GeneralSettings = [:units, :unit_multiplier, :default_weight, :handling_fee, 
      :max_weight_per_package, :test_mode]

    @config = Spree::ActiveShippingConfiguration.new
  end

  def update
    config = Spree::ActiveShippingConfiguration.new

    params.each do |name, value|
      next unless config.has_preference? name
      config[name] = value
    end

    redirect_to edit_admin_active_shipping_settings_path
  end

end

gem_hack/spree_active_shipping_2_4_0/app/views/spree/admin/active_shipping_settings/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:active_shipping_settings) %>
<% end %>

<%= form_tag admin_active_shipping_settings_path, :method => :put  do |form| %>
  <div id="preferences" data-hook>
    <fieldset class="general no-border-top">
      <div class="row">
        <div class="alpha six columns">
          <fieldset class="security no-border-bottom">
            <legend align="center"><%= Spree.t(:ups_settings)%></legend>
            <% @preferences_UPS.each do |key|
                type = @config.preference_type(key) %>
                <div class="field">
                  <%= label_tag(key, Spree.t(key) + ': ') + tag(:br) if type != :boolean %>
                  <%= preference_field_tag(key, @config[key], :type => type) %>
                  <%= label_tag(key, Spree.t(key)) + tag(:br) if type == :boolean %>
                </div>
            <% end %>
          </fieldset>
        </div>
        <div class="omega six columns">
          <fieldset class="currency no-border-bottom">
            <legend align="center"><%= Spree.t(:fedex_settings)%></legend>
            <% @preferences_FedEx.each do |key|
                type = @config.preference_type(key) %>
                <div class="field">
                  <%= label_tag(key, Spree.t(key) + ': ') + tag(:br) if type != :boolean %>
                  <%= preference_field_tag(key, @config[key], :type => type) %>
                  <%= label_tag(key, Spree.t(key)) + tag(:br) if type == :boolean %>
                </div>
            <% end %>
          </fieldset>
        </div>
      </div>

      <div class="row">
        <div class="alpha six columns">
          <fieldset class="security no-border-bottom">
            <legend align="center"><%= Spree.t(:usps_settings)%></legend>
            <% @preferences_USPS.each do |key|
                type = @config.preference_type(key) %>
                <div class="field">
                  <%= label_tag(key, Spree.t(key) + ': ') + tag(:br) if type != :boolean %>
                  <%= preference_field_tag(key, @config[key], :type => type) %>
                  <%= label_tag(key, Spree.t(key)) + tag(:br) if type == :boolean %>
                </div>
            <% end %>
          </fieldset>
        </div>
        <div class="omega six columns">
          <fieldset class="currency no-border-bottom">
            <legend align="center"><%= Spree.t(:canada_post_settings)%></legend>
            <% @preferences_CanadaPost.each do |key|
                type = @config.preference_type(key) %>
                <div class="field">
                  <%= label_tag(key, Spree.t(key) + ': ') + tag(:br) if type != :boolean %>
                  <%= preference_field_tag(key, @config[key], :type => type) %>
                  <%= label_tag(key, Spree.t(key)) + tag(:br) if type == :boolean %>
                </div>
            <% end %>
          </fieldset>
        </div>
      </div>

      <div class="row">
        <div class="alpha six columns">
          <fieldset class="currency no-border-bottom">
            <legend align="center"><%= Spree.t(:general_settings)%></legend>
            <% @preferences_GeneralSettings.each do |key|
                type = @config.preference_type(key) %>
                <div class="field">
                  <%= label_tag(key, Spree.t(key) + ': ') + tag(:br) if type != :boolean %>
                  <%= preference_field_tag(key, @config[key], :type => type) %>
                  <%= label_tag(key, Spree.t(key)) + tag(:br) if type == :boolean %>
                </div>
            <% end %>
          </fieldset>
        </div>
      </div>

      <div class="form-buttons filter-actions actions" data-hook="buttons">
        <%= button Spree.t(:update), 'icon-refresh' %>
        <span class="or"><%= Spree.t(:or) %></span>
        <%= link_to_with_icon 'icon-remove', Spree.t(:cancel), edit_admin_active_shipping_settings_url, :class => 'button' %>
      </div>

    </fieldset>
  </div>
<% end %>